<!doctype html>
<html>
<head>
    <title>BOOM! : Procedural SVG Generator</title>
    <link href="http://fonts.googleapis.com/css?family=Holtwood+One+SC" rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Lato:300,300italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/boom.css"/>
</head>
<body>
    <div class="outer" id="top">
        <div class="inner">
            <h1>BOOM!</h1>
            <h2>Procedural SVG Generator</h2>
            <a class="button" href="generator.php">Start generating</a>
        </div>
    </div>
    <div class="outer" id="content">
        <div class="inner">
            <h3>Examples</h3>
            <?php /* <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul> */ ?>
            <em>coming soon ...</em>
        </div>
    </div>
    <div class="outer" id="footer">
        <div class="inner">
            <p>Generated by <a href="http://gielberkers.com">Giel Berkers</a></p>
        </div>
    </div>
</body>
</html>